# Nome da aplicação
spring.application.name=marmita-manager

# Conexão com o banco (precisa bater com o que definimos no docker-compose.yml)
spring.datasource.url=jdbc:postgresql://localhost:5432/marmita_manager
spring.datasource.username=marmita_user
spring.datasource.password=marmita_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA: cria/atualiza tabelas automaticamente baseado nas Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto do Postgres (ajuda o Hibernate a gerar SQL otimizado pra esse banco específico)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs